# ImageStream - Defines the image repository for alert-consumer
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: alert-consumer
  labels:
    app: alert-consumer
spec:
  lookupPolicy:
    local: true
---
# BuildConfig - Builds the alert consumer image from source
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: alert-consumer
  labels:
    app: alert-consumer
spec:
  resources:
    limits:
      memory: 1Gi
      cpu: '1'
    requests:
      memory: 256Mi
      cpu: 200m
  source:
    type: Git
    git:
      uri: https://github.com/IANDYI/care-service.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.alert-consumer
      buildArgs:
        - name: DOCKER_BUILDKIT
          value: "1"
  output:
    to:
      kind: ImageStreamTag
      name: alert-consumer:latest
  triggers:
    - type: ConfigChange
---
# ConfigMap for Alert Consumer configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-consumer-config
  labels:
    app: alert-consumer
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672/"
  ALERTS_QUEUE_NAME: "baby_alerts"
  WEBSOCKET_PORT: "8081"
---
# Deployment for Alert Consumer
# This consumer runs separately from the care-service and processes
# alert messages published by the care-service when measurements
# have Red safety status.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-consumer
  labels:
    app: alert-consumer
    component: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-consumer
      component: consumer
  template:
    metadata:
      labels:
        app: alert-consumer
        component: consumer
    spec:
      containers:
        - name: alert-consumer
          image: alert-consumer:latest
          command: ["./alert-consumer"]
          ports:
            - containerPort: 8081
              name: websocket
            - containerPort: 8081
              name: metrics
          envFrom:
            - configMapRef:
                name: alert-consumer-config
          env:
            - name: WEBSOCKET_PORT
              value: "8081"
            - name: PUBLIC_KEY_PATH
              value: "/etc/certs/public.pem"
          volumeMounts:
            - name: public-key
              mountPath: /etc/certs
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          # Health check - HTTP endpoint
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: public-key
          secret:
            secretName: identity-rsa-keys
            items:
              - key: public.pem
                path: public.pem
---
# Service for Alert Consumer (WebSocket and metrics)
apiVersion: v1
kind: Service
metadata:
  name: alert-consumer
  labels:
    app: alert-consumer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: alert-consumer
    component: consumer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: websocket
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: metrics
  type: ClusterIP
---
# Route for Alert Consumer WebSocket (optional, for external access)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: alert-consumer-ws
  labels:
    app: alert-consumer
spec:
  to:
    kind: Service
    name: alert-consumer
    weight: 100
  port:
    targetPort: websocket
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
# Note: The alert consumer is a separate service that:
# - Listens to the "baby_alerts" RabbitMQ queue
# - Processes alert messages published by care-service when measurements have Red status
# - Logs alerts and writes them to /tmp/alerts_received.json for verification
# - Runs independently from the care-service API
#
# The baby consumer (for baby creation requests) runs as a goroutine
# inside the care-service pod and does NOT need a separate deployment.
